enable-magisk-update = false
parallel-jobs = 1

patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "Anddea"
patches-version = "dev"

[YT-A]
app-name = "YouTube"
patcher-args = "-e 'Custom branding icon for YouTube' -OrestoreOldSplashAnimation=true -e 'Settings for YouTube' -OrvxSettingsLabel=Anddea -e 'Visual preferences icons for YouTube' -OsettingsMenuIcon=rvx_letters_bold -OapplyToAll=false"
included-patches = "'Custom branding name for YouTube' 'Custom header for YouTube' 'Hide shortcuts' 'Theme'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"

[YTM-A]
app-name = "Music"
patcher-args = "-e 'Custom branding icon for YouTube Music' -OrestoreOldSplashIcon=true -e 'Custom branding name for YouTube Music' -OappNameLauncher=Music -OappNameNotification=Music -e 'Settings for YouTube Music' -OrvxSettingsLabel=Anddea -e 'Visual preferences icons for YouTube Music' -OsettingsMenuIcon=rvx_letters_bold -OapplyToAll=false"
included-patches = "'Custom header for YouTube Music'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
arch = "arm64-v8a"
